### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by Heiner92** [Caleb9/SynologyPhotosAlbumList#4]
Hi there,

your CLI tool looks to be what I want. However I did not manage to use the pre-built windows .exe. I get this error message. Can this be fixed with additional build flags?

```Unhandled exception. System.AggregateException: One or more errors occurred. (Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.)
 ---> System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
   at System.Text.Json.JsonSerializer.DeserializeAsync[TValue](Stream , JsonSerializerOptions , CancellationToken )
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent, JsonSerializerOptions, CancellationToken)
   at SynologyPhotosUtil.SynologyApi.sendRequest@19.MoveNext()
   at SynologyPhotosUtil.SynologyApi.sendRequest@19.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken, FSharpAsync`1, FSharpOption`1) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1140
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken, FSharpAsync`1, FSharpOption`1) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1167
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1, FSharpOption`1 , FSharpOption`1 ) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1511```

**Comment by Caleb9** [comment]
Hi @Heiner92, I was able to reproduce the error. Give me some time to investigate.

**Comment by Caleb9** [comment]
@Heiner92 can you try if the [new release 0.2.2](https://github.com/Caleb9/SynologyPhotosUtil/releases/tag/0.2.2) works? Thanks.

**Comment by Heiner92** [comment]
I manged to get going with the new build. Thank you very much :)
